name: Build Verification
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

concurrency:
  group: verify-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-build:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          setup-python: "false"
          cache: "true"
          dir: ${{ runner.temp }}

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cmake generate
        run: cmake -DCMAKE_PREFIX_PATH=${{env.QT_ROOT_DIR}} -S . -B build

      - name: Cmake build
        run: cmake --build build --config Release

      - name: Verify executable was created
        id: verify_exe
        run: |
          if (Test-Path "build\Release\StrataBro.exe") {
            Write-Host "✅ Build successful - executable created"
            echo "status=success" >> $env:GITHUB_OUTPUT
            echo "emoji=✅" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "❌ Build failed - executable not found"
            echo "status=failure" >> $env:GITHUB_OUTPUT
            echo "emoji=❌" >> $env:GITHUB_OUTPUT
            exit 1
          }

      - name: Add build summary
        if: always()
        run: |
          $status = "${{ steps.verify_exe.outputs.status }}"
          $emoji = "${{ steps.verify_exe.outputs.emoji }}"
          
          if ("$status" -eq "success") {
            $result = "✅ Success"
            $details = "StrataBro.exe was successfully built"
            $fileSize = (Get-Item "build\Release\StrataBro.exe").Length / 1MB
            $fileSize = [math]::Round($fileSize, 2)
            $buildTime = "${{ job.duration }}"
          } else {
            $result = "❌ Failure"
            $details = "StrataBro.exe was not found"
            $fileSize = "N/A"
            $buildTime = "${{ job.duration }}"
          }
          
          $summary = @"
          ## Build Verification Results
          
          | Status | Details | File Size | Build Time |
          | ------ | ------- | --------- | ---------- |
          | $result | $details | ${fileSize} MB | $buildTime |
          
          ### Build Information
          - Commit: ${{ github.sha }}
          - Branch: ${{ github.ref_name }}
          - Triggered by: ${{ github.actor }}
          - Build date: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
          "@
          
          $summary | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding UTF8