name: Build Verification
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

concurrency:
  group: verify-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-build:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          setup-python: "false"
          cache: "true"
          dir: ${{ runner.temp }}

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cmake generate
        run: cmake -DCMAKE_PREFIX_PATH=${{env.QT_ROOT_DIR}} -S . -B build

      - name: Cmake build
        run: cmake --build build --config Release

      - name: Verify executable was created
        run: |
          if (Test-Path "build\Release\StrataBro.exe") {
            Write-Host "✅ Build successful - executable created"
          } else {
            Write-Host "❌ Build failed - executable not found"
            exit 1
          }