name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
permissions:
  contents: read

concurrency:
  group: build-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          setup-python: "false"
          cache: "true"
          dir: ${{ runner.temp }}
          
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cmake generate
        run: ${{env.QT_ROOT_DIR}}\bin\qt-cmake.bat -G Ninja -S . -B build

      - name: Cmake build
        run: cmake --build build --config Release

      - name: Cmake deploy dependencies
        run: ${{env.QT_ROOT_DIR}}\bin\windeployqt.exe --release --no-translations build\StrataBro.exe

      - name: List contents of the build directory
        run: ls -R build
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: StrataBro
          path: |
              build\Release*.exe
              build\Release*.dll
          retention-days: 1