name: Create Package
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build package from'
        required: true
        default: 'master'
        type: string

permissions:
  contents: read

jobs:
  create-package:
    runs-on: windows-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          setup-python: "false"
          cache: "true"

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Cmake generate and build
        run: |
          cmake -DCMAKE_PREFIX_PATH=${{env.QT_ROOT_DIR}} -S . -B build
          cmake --build build --config Release

      - name: Deploy with windeployqt
        run: |
          $deployDir = "deploy"
          New-Item -ItemType Directory -Path $deployDir -Force
          Copy-Item "build\Release\StrataBro.exe" -Destination $deployDir
          & ${{env.QT_ROOT_DIR}}\bin\windeployqt.exe --release --no-compiler-runtime $deployDir\StrataBro.exe

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: StrataBro
          path: deploy
          retention-days: 30