name: Create Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-windows-release:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          setup-python: "false"
          cache: "true"
          dir: ${{ runner.temp }}

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Get version
        id: get_version
        run: |
          $version = Get-Content -Path "VERSION.txt" -Raw
          $version = $version.Trim()
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Cmake generate
        run: cmake -DCMAKE_PREFIX_PATH=${{env.QT_ROOT_DIR}} -S . -B build

      - name: Cmake build
        run: cmake --build build --config Release

      - name: Run deployment target
        run: cmake --build build --target WinDeploy --config Release

      - name: Create version info file
        run: |
          $version = "${{ steps.get_version.outputs.VERSION }}"
          $commitSha = "${{ github.sha }}".Substring(0, 8)
          $buildDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
          
          $content = @"
          Version: $version
          Commit: $commitSha
          Build Date: $buildDate
          "@
          
          Set-Content -Path "build/deploy/build_info.txt" -Value $content

      - name: Create release ZIP
        run: |
          Compress-Archive -Path build/deploy/* -DestinationPath "StrataBro-${{ steps.get_version.outputs.VERSION }}.zip"

      - name: Upload build to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: "StrataBro-${{ steps.get_version.outputs.VERSION }}.zip"
          append_body: true
          token: ${{ secrets.ADMIN_TOKEN }}